### ISSUE TITLE
Symfony 2.8 Deprecations

### ISSUE THREAD

**Issue by dkisselev** [rybakit/RybakitNavigationBundle#9]
A few deprecations from the Symfony deprecation debug bridge:

Defining the initRuntime() method in the "rybakit_navigation" extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).

The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead.

https://github.com/rybakit/RybakitNavigationBundle/blob/master/Navigation/Filter/UrlFilter.php#L30

**Comment by rybakit** [comment]
@dkisselev Could you please check if it's OK now?

**Comment by dkisselev** [comment]
Thanks @rybakit, deprecation log looks clean to me :+1:
